config/routes.rb
KickStarter::Application.routes.draw do

  root to: "api/static_pages#root"
  # root to: 'users#index'
  resources :users do
    resources :user_bio, only: [:new]
  end
  resource :session, only: [:new, :create]
  get "/session", to: "sessions#destroy"

  namespace :api, defaults: { format: :json} do
    get '/users', as: :get_current_user, to: 'users#get_current_user'
    resources :users, only: [:gest_current_user,:create, :update, :show]
    resources :projects, only: [:show, :create, :update]
    resources :rewards, only: [:create, :show]
    resources :claimed_rewards, only: [:create]
    resources :catagories, only: [:show]
    resources :stories, only: [:create, :update]
    resources :comments, only: [:create, :show]
    resources :messages, only: [:create]
    resource :session, only: [:create, :destroy]
  end

  resources :user_bio, only: [:create, :edit, :update, :destroy]
  resources :catagories, only: [:index, :show]

  resources :projects, only: [:new, :create, :edit, :update, :destroy, :show] do
    resources :rewards, only: [:new, :index]
    resources :stories, only: [:new, :index]
  end

  resources :rewards, only: [:create, :edit, :update, :destroy]
  resources :stories, only: [:create, :edit, :update, :destroy]
  resources :claimed_rewards, only: [:create]
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to  :project, class_name: "Project"
  belongs_to  :backer,  class_name: "Users", foreign_key: :backer_id, primary_key: :id
  has_one     :maker,   through: :project, source: :user
  has_many    :duplicates, class_name: "Reward", foreign_key: :id, primary_key: :id
  has_many    :claimed_rewards, class_name: "ClaimedRewards", foreign_key: :reward_id
  #validate quantity left
  def times_backed
    duplicates.count
  end
end

app/controllers/api/rewards_controller.rb
module Api
  class RewardsController < ApplicationController

    def show
      @reward = Reward.find(params[:id])

      render :reward_show
    end

    def create
      @reward = Reward.new(reward_params)

      if @reward.save
        render json: @reward
      else
        puts @project.errors.full_messages
        render json: @project.errors.full_messages, status: :unprocessable_entity
      end
    end

    def reward_params
      params.require(:reward).permit(:backer_id, :project_id, :pledge_amt, :description, :est_delivery, :qty)
    end

  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

    before_filter :require_logged_in, except: [:show]

  def index
    @rewards = Reward.where(project_id: params[:project_id])
  end

  def new
    @reward = Reward.new(project_id: params[:project_id])
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      redirect_to  project_rewards_url(@reward.project_id)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    if @reward.update_attributes(reward_params)
      redirect_to project_rewards_url(@reward.project_id)
    else
      flash.now[:errors] = @reward.errors.full_messages
      render :edit
    end


  end

  def show
    @reward = Reward.find(params[:id])
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    redirect_to rewards_url
  end

  private

  def reward_params
    params.require(:reward).permit(:backer_id, :project_id, :pledge_amt, :description, :est_delivery, :qty)
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_reward_project.html.erb
<dive class="reward-project">
  <form action="<%= claimed_rewards_url %>">
    <input type="hidden" name="claimed[project_id]" value="<%= project.id %>">
    <input type="hidden" name="claimed[user_id]" value="<%= user.id %>">
  <h3>reward</h3>
  <p>pledge $<%= reward.pledge_amt %></p>
  <p> Backers</p>
  <p>Desription</p>
  <p><%= reward.description %></p>
  </form>
</dive>

app/views/rewards/_rewardform.html.erb
<% action = (reward.persisted? ? reward_url(reward) : rewards_url ) %>
<% url_method = (reward.persisted? ? "PATCH" : "POST" ) %>



<form action="<%= action %>" method="POST" class="form">
  <input type="hidden" name="_method" value="<%= url_method %>">
  <%= form_auth %>
   <input type="hidden" name="reward[backer_id]" value="<%= current_user.id %>">
   <input type="hidden" name="reward[project_id]" value="<%= reward.project_id %>">

    <br>
  <label for="pledge">Pledge</label>
    <br>
  <input type="text" name="reward[pledge_amt]" value="<%= reward.pledge_amt %>" id="pledge">
    <br>
  <leabel for="description">Description</leabel>
    <br>
  <textarea id="description" name="reward[description]"><%= reward.description %></textarea>
    <br>
  <label for="estimated_delivery">Estimated Delivery</label>
    <br>
  <input type="date" name="reward[est_delivery]" value="<%= reward.est_delivery %>" id="estimated_delivery">
    <br>
  <label for="limited_quantity">Limited Quantity</label>
    <br>
  <input type="text" name="reward[qty]" value="<%= reward.qty %>" id="limited_quantity">

  <input type="submit" value="save">
</form>

app/views/rewards/edit.html.erb
<h2>Edit Your Reward</h2>

<%= render partial: "rewardform", locals: { reward: @reward }%>

app/views/rewards/index.html.erb
<h2>How Will You Thank People</h2>

<% project_id = @rewards.first.project_id %>

<ul>

    <% @rewards.each do |reward| %>

    <li><%= render partial: "rewardform", locals: { reward: reward } %></li>

    <% end %>


</ul>

<a href="<%= new_project_story_url(project_id) %>">Save</a>

app/views/rewards/new.html.erb
<h2>How Will You Thank People</h2>

<%= render partial: "rewardform", locals: { reward: @reward }%>