config/routes.rb
KickStarter::Application.routes.draw do

  root to: "api/static_pages#root"
  # root to: 'users#index'
  resources :users do
    resources :user_bio, only: [:new]
  end
  resource :session, only: [:new, :create]
  get "/session", to: "sessions#destroy"

  namespace :api, defaults: { format: :json} do
    get '/users', as: :get_current_user, to: 'users#get_current_user'
    resources :users, only: [:gest_current_user,:create, :update, :show]
    resources :projects, only: [:show, :create, :update]
    resources :rewards, only: [:create, :show]
    resources :claimed_rewards, only: [:create]
    resources :catagories, only: [:show]
    resources :stories, only: [:create, :update]
    resources :comments, only: [:create, :show]
    resources :messages, only: [:create]
    resource :session, only: [:create, :destroy]
  end

  resources :user_bio, only: [:create, :edit, :update, :destroy]
  resources :catagories, only: [:index, :show]

  resources :projects, only: [:new, :create, :edit, :update, :destroy, :show] do
    resources :rewards, only: [:new, :index]
    resources :stories, only: [:new, :index]
  end

  resources :rewards, only: [:create, :edit, :update, :destroy]
  resources :stories, only: [:create, :edit, :update, :destroy]
  resources :claimed_rewards, only: [:create]
end

app/models/catagorie.rb
class Catagorie < ActiveRecord::Base
  CATAGORIES = [
    :technology,
    :food,
    :dance,
    :design,
    :games
  ]
  has_many :projects, class_name: "Project", foreign_key: :catagory_id, primary_key: :catagory
end

app/models/claimed_rewards.rb
class ClaimedRewards < ActiveRecord::Base
  belongs_to :user,   class_name: "Users", foreign_key: :user_id
  belongs_to :reward, class_name: "Reward", foreign_key: :reward_id
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :project
  belongs_to :user, class_name: "Users"
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :image, polymorphic: true
  has_attached_file :pic, :styles => {
    :big => "600x600#",
    :small => "50x50#",
    :thumb => "28x28#",
    
  }

  validates_attachment_content_type(
    :pic,
    :content_type => /\Aimage\/.*\Z/
  )

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates   :title,     :title, :user_id, presence: true
  validates   :title,     uniqueness: true

  has_many    :rewards,         class_name: "Reward"
  has_one     :story,           class_name: "Story",        foreign_key: :project_id
  has_many    :youtube_code,    class_name: "YoutubeCode",  foreign_key: :project_id
  has_many    :claimed_rewards, through: :rewards,          source: :claimed_rewards
  has_many    :comment,         class_name: "Comment"
  belongs_to  :user,            class_name: "Users",        foreign_key: :user_id,      primary_key: :id
  belongs_to  :catagory,        class_name: "Catagorie",    foreign_key: :catagory_id,  primary_key: :catagory

  has_many    :pictures, as: :image

  def backers
    claimed_rewards.map do |claimed|
      claimed.user.id
    end
  end

  def amt_pledged
    claimed = claimed_rewards.map { |claimed| claimed.reward.pledge_amt }.inject(:+)

    claimed.nil? ? 0 : claimed
  end

  def how_many_backers
    backers.count
  end

  def username
    return if user.user_bio.nil?
    user.user_bio.username
  end

  def project_story
    return if story.nil?
    story.story
  end

  def project_challenges
    return if story.nil?
    story.challenges
  end

  def percent_funded
    return 0 if amt_pledged == 0
    (amt_pledged * 100)/self.fundinggoal.to_i
  end

  def comment_count
    comment.count
  end

  def vcode
    youtube_code.first.vcode
  end

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to  :project, class_name: "Project"
  belongs_to  :backer,  class_name: "Users", foreign_key: :backer_id, primary_key: :id
  has_one     :maker,   through: :project, source: :user
  has_many    :duplicates, class_name: "Reward", foreign_key: :id, primary_key: :id
  has_many    :claimed_rewards, class_name: "ClaimedRewards", foreign_key: :reward_id
  #validate quantity left
  def times_backed
    duplicates.count
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :project, class_name: "Project", foreign_key: :project_id
end

app/models/user_bio.rb
class UserBio < ActiveRecord::Base
  belongs_to :users, class_name: "Users", foreign_key: :user_id, primary_key: :id
end

app/models/users.rb
class Users < ActiveRecord::Base
  attr_reader :password
  validates :email, presence: true, uniqueness: true, if: :editing_email
  validates :session_token, presence: true, uniqueness: true
  validates :password_digest, length: { minimum: 6, allow_nil: true }

  has_many  :rewards,          through: :claimed_rewards, source: :reward
  has_many  :projects,            class_name: "Project",         foreign_key: :user_id,    primary_key: :id
  has_one   :user_bio,            class_name: "UserBio",         foreign_key: :user_id,    primary_key: :id
  has_many  :claimed_rewards,     class_name: "ClaimedRewards",  foreign_key: :user_id
  has_many  :comments,            class_name: "Comment",         foreign_key: :user_id
  has_many  :received_messages,   class_name: "Message",        foreign_key: :to_user_id,   primary_key: :id
  has_many  :sent_messages,       class_name: "Message",        foreign_key: :from_user_id, primary_key: :id

  has_many  :backed_projects,  through: :rewards,      source: :project
  has_many  :pictures, as: :image



   after_initialize :ensure_session

  def self.find_by_credentials(email, password)
    user = Users.find_by_email(email)
    user.try(:is_password?, password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end

  def editing_email
    true unless Users.find_by_email(:email)
  end

  def name
    user_bio.username
  end

  def number_of_backed_projects
    backed_projects.count
  end

  def number_of_projects
    projects.count
  end

end

app/models/youtube_code.rb
class YoutubeCode < ActiveRecord::Base
  belongs_to :project, class_name: "Project", foreign_key: :project_id
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/user_bios_helper.rb
module UserBiosHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KickStarter</title>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>

  <main>
  <%= render 'shared/header_and_errors' %>
</main>
<div class="main-body"></div>
<%= yield %>

 <script>
  <% if logged_in? %>
    window.currentUserId = <%= current_user.id %>
    window.formAuth = "<%= form_authenticity_token %>"

  <% end %>


</script>
</body>
</html>

app/views/shared/_bio_new_or_edit_link.html.erb
<% which_url = ( !current_user.user_bio.nil? ? edit_user_bio_url(current_user.user_bio.id) : new_user_user_bio_url(current_user) )%>
   <a href="<%= which_url %>">Settings</a>
   <a href="<%= user_url(current_user) %>">Profile</a>

app/views/shared/_header.html.erb
<div class="group header">

  <a href="<%= users_url %>" class="title">KickStarter</a>
  <a href="<%= catagories_url %>" class="discover-start">Discover</a>
  <a href="<%= new_project_url %>" class="discover-start">Start</a>
  <% if logged_in? %>
  <div class="user-tab">Me</div>
  <div class="user-info-header-dropdown">
     <%= render "shared/bio_new_or_edit_link" %>
     <p>Your are signed in as: <%= current_user.user_bio.nil? ? "Guest" : current_user.user_bio.username  %></p>

     <%= button_to "Sign Out", session_url, method: :delete %>
     <div class="current-project-dropdown">
       <p>Your Projects</p>
       <br>
       <ul>
         <% if !current_user.projects.empty? %>
           <% current_user.projects.each do |project| %>

             <li><a href="<%= project_url(project) %>"><%=  project.title %></a></li>

           <% end %>
         <% end %>

       </ul>
       <br>
       <p>Projects You Have Backed</p>
       <br>
       <ul>
         <% if !current_user.projects.empty? %>
           <% current_user.backed_projects.each do |project| %>

             <li><a href="<%= project_url(project) %>"><%=  project.title %></a></li>

           <% end %>
         <% end %>

       </ul>
     </div>
  </div>


  <% else %>

    <div class="user-tab group">
      <a href="<%= new_user_url %>" >Sign up</a>
      <a href="<%= new_session_url %>">Sign In</a>
    </div>

  <% end %>
</div>

app/views/shared/_header_and_errors.html.erb
  <%= render "shared/header" %>
  <ul>
  <% if flash[:errors] %>

    <% flash[:errors]. each do |error| %>

      <li><%= error %> error</li>

    <% end %>

  <% end %>
</ul>