config/routes.rb
KickStarter::Application.routes.draw do

  root to: "api/static_pages#root"
  # root to: 'users#index'
  resources :users do
    resources :user_bio, only: [:new]
  end
  resource :session, only: [:new, :create]
  get "/session", to: "sessions#destroy"

  namespace :api, defaults: { format: :json} do
    get '/users', as: :get_current_user, to: 'users#get_current_user'
    resources :users, only: [:gest_current_user,:create, :update, :show]
    resources :projects, only: [:show, :create, :update]
    resources :rewards, only: [:create, :show]
    resources :claimed_rewards, only: [:create]
    resources :catagories, only: [:show]
    resources :stories, only: [:create, :update]
    resources :comments, only: [:create, :show]
    resources :messages, only: [:create]
    resource :session, only: [:create, :destroy]
  end

  resources :user_bio, only: [:create, :edit, :update, :destroy]
  resources :catagories, only: [:index, :show]

  resources :projects, only: [:new, :create, :edit, :update, :destroy, :show] do
    resources :rewards, only: [:new, :index]
    resources :stories, only: [:new, :index]
  end

  resources :rewards, only: [:create, :edit, :update, :destroy]
  resources :stories, only: [:create, :edit, :update, :destroy]
  resources :claimed_rewards, only: [:create]
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates   :title,     :title, :user_id, presence: true
  validates   :title,     uniqueness: true

  has_many    :rewards,         class_name: "Reward"
  has_one     :story,           class_name: "Story",        foreign_key: :project_id
  has_many    :youtube_code,    class_name: "YoutubeCode",  foreign_key: :project_id
  has_many    :claimed_rewards, through: :rewards,          source: :claimed_rewards
  has_many    :comment,         class_name: "Comment"
  belongs_to  :user,            class_name: "Users",        foreign_key: :user_id,      primary_key: :id
  belongs_to  :catagory,        class_name: "Catagorie",    foreign_key: :catagory_id,  primary_key: :catagory

  has_many    :pictures, as: :image

  def backers
    claimed_rewards.map do |claimed|
      claimed.user.id
    end
  end

  def amt_pledged
    claimed = claimed_rewards.map { |claimed| claimed.reward.pledge_amt }.inject(:+)

    claimed.nil? ? 0 : claimed
  end

  def how_many_backers
    backers.count
  end

  def username
    return if user.user_bio.nil?
    user.user_bio.username
  end

  def project_story
    return if story.nil?
    story.story
  end

  def project_challenges
    return if story.nil?
    story.challenges
  end

  def percent_funded
    return 0 if amt_pledged == 0
    (amt_pledged * 100)/self.fundinggoal.to_i
  end

  def comment_count
    comment.count
  end

  def vcode
    youtube_code.first.vcode
  end

end

app/controllers/api/projects_controller.rb
module Api
  class ProjectsController < ApplicationController

    def show
      puts "!!!!!!!!!!!!!!#$$$$$$$$$$$"
      @project = Project.find(params[:id])
      puts @project.title
      render :project
    end

    def create
      puts params
      @project = Project.new(project_params)

      if @project.save

        # @project.pictures.destroy if !photo_params.empty? && !@project.pictures.nil?

        @project.pictures.create!(photo_params)
        puts "!!!!!!!!!!!!!!!!!!"
        puts photo_params
        puts @project.pictures
        puts"!!!!!!!!!!!!!!!!!!!!!!"
        render json: @project
      else
        render json: @project.errors.full_messages, status: :unprocessable_entity
      end
    end

    def update
      puts params
      @project = Project.find(params[:id])

      if @project.update(project_params)
        render json: @project
      else
        puts @project.errors.full_messages
        render json: @project.errors.full_messages, status: :unprocessable_entity
      end

    end

    private

    def project_params
      params.require(:project).permit(:user_id, :description, :title, :catagory_id, :duration, :fundinggoal)
    end

    def photo_params
      params.permit(:pic)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :store_location, only: [:new, :edit]
  before_filter :require_logged_in, except: [:show]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
       @catagorie = Catagorie.new(catagory: @project.catagory_id, project_id: @project.id)
       @catagorie.save
      # redirect to new rewards
      redirect_to project_rewards_url(@project)
      #new_project_reward_url(@project)
    else
      flash.now[:errors] =  @project.errors.full_messages
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
     @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      redirect_to users_url
    else
      flash.now[:errors] = @project.errors.full_messages
      render :edit
    end

  end

  def show
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to user_url(@project.user_id)
  end

  private

  def project_params
    params.require(:project).permit(:user_id, :description, :title, :catagory_id, :duration, :fundinggoal)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project_image_title.html.erb
<div class="project-thumbnail-large group">
  <a href="<%= project_url(project) %>"><image class="user-image"></a>
    <p class="project-title"><%= project.title %></p>
</div>

app/views/projects/_projectblurb.html.erb
<div class="project-blurb">
  <a><%= project.title %></a>
  <br>
  <a><%= current_user.name %></a>
  <br>
  <a><%= project.description[0...34] %></a>
  <br>
  <a><%= project.catagory.catagory %></a>
  <br>
  <a><%= project.title %></a>
  <br>
  <a><%= "canceled" if project.active == true %></a>
</div>

app/views/projects/_projectform.html.erb
<% action = (project.persisted? ? project_url(project) : projects_url) %>
<% url_method = (project.persisted? ? "PATCH" : "POST") %>
<% title = (project.persisted? ? "Edit Your Porject" : "What are you going to create") %>
<h2><%= title %></h2>

<form class="form start-project-form " action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= url_method %>">

  <input type="hidden" name="project[user_id]" value="<%= current_user.id %>">
  <%= form_auth %>
  <br>
  <label for="title">Title</label>
  <br>
  <input type="text" name="project[title]" id="title" value="<%= project.title %>">
  <br>
  <leabel for="description">Shrot blurb</leabel>
  <br>
  <textarea id="description" name="project[description]"><%= project.description %></textarea>
  <br>
  <leabel for="cat">Catagorie</leabel>
  <br>
  <!-- <input type="text" name="project[catagorie]" id="cat"> -->
  <select name="project[catagory_id]" id="cat">
    <% Catagorie::CATAGORIES.each do |cat| %>
      <option <%= selected if cat == project.catagory_id %>><%= cat %></option>
    <% end %>
  </select>
  <br>
  <leabel for="duration">Funding Duration</leabel>
  <br>
  <input type="text" name="project[duration]" id="duration" value="<%= project.duration %>">
  <br>
  <leabel for="goal">Funding Goal</leabel>
  <br>
  <input type="text" name="project[fundinggoal]" id="goal" value="<%= project.fundinggoal %>">
  <br>
  <input type="submit" value="submit">
</form>

app/views/projects/edit.html.erb
<%= render partial: "projectform", locals: { project: @project } %>

app/views/projects/new.html.erb
<% action = (@project.persisted? ? edit_project_url(@project) : projects_url) %>
<% url_method = (@project.persisted? ? "PATCH" : "POST") %>
<% title = (@project.persisted? ? "Edit Your Porject" : "What are you going to create") %>
<h2><%= title %></h2>

<form class="start-project-form" action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= url_method %>">

  <input type="hidden" name="project[user_id]" value="<%= current_user.id %>">
  <%= form_auth %>
  <br>
  <label for="title">Title</label>
  <br>
  <input type="text" name="project[title]" id="title" value="<%= @project.title %>">
  <br>
  <leabel for="description">Shrot blurb</leabel>
  <br>
  <textarea id="description" name="project[description]"><%= @project.description %></textarea>
  <br>
  <leabel for="cat">Catagorie</leabel>
  <br>
  <!-- <input type="text" name="project[catagorie]" id="cat"> -->
  <select name="project[catagory_id]" id="cat">
    <% Catagorie::CATAGORIES.each do |cat| %>
      <option <%= selected if cat == @project.catagory_id %>><%= cat %></option>
    <% end %>
  </select>
  <br>
  <leabel for="duration">Funding Duration</leabel>
  <br>
  <input type="text" name="project[duration]" id="duration" value="<%= @project.duration %>">
  <br>
  <leabel for="goal">Funding Goal</leabel>
  <br>
  <input type="text" name="project[fundinggoal]" id="goal" value="<%= @project.fundinggoal %>">
  <br>
  <input type="submit" value="submit">
</form>

app/views/projects/show.html.erb
<div class="background-project">
  <div class="user-edit">
    <% if current_user.id == @project.user_id %>

      <a href="<%= edit_project_url(@project) %>">Edit This Project</a>
      <a href="<%= project_rewards_url(@project) %>">Edit Rewards</a>
      <a href="<%= edit_story_url(@project.story.id) %>">Edit Story</a>
       <%= button_to "Delete Project", project_url(@project), method: :delete %>
    <% end %>
  </div>

  <div class="project-runner">
    <div class="container">
        <h2><%= @project.title %></h2>
        <a href=""><%= @project.user.user_bio.username %></a>
    </div>
    <a ><%= @project.catagory_id %></a>
  </div>

  <div class="project-main group">



    <div class="project-body group">

      <image class="user-video">
      <br>
      <h3>Our Story</h3>
      <a><%= @project.story.story %></a>
      <br>
      <h3>Challenges</h3>
      <a><%= @project.story.challenges %></a>

    </div>

      <div class="right-container">
        <br>
        <h1><%= @project.how_many_backers %> </h1>
        <p>Backers</p>
        <br>
        <h1>$<%= @project.amt_pledged %> </h1>
        <p>pledged of a <%= @project.fundinggoal %></p>
        <br>

        <h1><%= @project.duration %></h1>
        <p>Days to go</p>

      </div>

      <div>
        <% @project.rewards.each do |reward| %>

          <div><%= render partial: "rewards/reward_project", locals: { project: @project, user: current_user, reward: reward }%></div>

        <% end %>
      </div>

  </div>
</div>